### ISSUE TITLE
Unable to reproduce results

### ISSUE THREAD

**Issue by divyagupta25** [ga1i13o/JIST#1]
Hi, 

Thanks for sharing the code and the model. 

I am unable to reproduce R@1 of 90.6 (Train on MSLS, Test on MSLS) and R@1 of 79 (Train on MSLS, Test on RobotCar). Instead, I am getting the following numbers 

| Dataset  | R@1 (Obtained) |
| ------------- | ------------- |
| MSLS - Copenhagen  | 87.6  |
| MSLS - San Francisco  | 90.4  |
| Oxford RobotCar  | 47.1  |

Below is a screenshot with configuration settings and output details for reference -

![jist_robotcar](https://github.com/ga1i13o/JIST/assets/30105023/eee4ad7e-e00f-4abc-a6a5-8229f7ae13f5)

**Comment by ga1i13o** [comment]
Hi, is this screen from running the eval script?
I see the resume_model arg is empty, so it would seem you are testing an untrained model with cosplace weights

**Comment by divyagupta25** [comment]
Yes, this screen is from running the below command - 
`python evaluation.py --resume JIST_r18_512_seqgem.pth --seq_dataset_path /path/to/robotcardataset`

The dataset is downloaded from the Google Drive link in the SeqVLAD repository. 

I see there are two different arguments `resume` and `resume_model`. I will check with the latter.

**Comment by divyagupta25** [comment]
It's matching now. You might want to update the Readme. 

Thanks!
